### ISSUE TITLE
Проверка ДЗ

### ISSUE THREAD

**Issue by ViktorZarvanskyi** [AbrLis/rsschool-cv#7]
Здравствуйте.
Пожалуйста напишите мне в дискорд @Хотящий (Виктор)#0487. 
Или оставьте здесь свой ник на дискорд, или другой способ связи с Вами. У меня есть вопросы по проверке моего ДЗ.

**Comment by AbrLis** [comment]
Напиши мне в телеграм @Lisinka. Не могу найти тебя в дискорде, так какая-то
дурацкая система личных сообщений, либо я в ней не могу разобраться. Либо
сообщи как ещё можно с тобой связаться.

чт, 14 июл. 2022 г. в 20:43, Viktor ***@***.***>:
